export const CATEGORIES_ACTION_TYPE = {
    FETCH_CATEGORY_START: 'category/FETCH_CATEGORY_START',
    FETCH_CATEGORY_FAILED: 'category/FETCH_CATEGORY_FAILED',
    FETCH_CATEGORY_SUCCESS: 'category/FETCH_CATEGORY_SUCCESS',
}